// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Remedin.Infrastructure.Persistence;

#nullable disable

namespace Remedin.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RemedinDbContext))]
    [Migration("20260905000000_PresentationPackaging")]
    partial class PresentationPackaging
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "unaccent");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Remedin.Domain.Ingestion.IngestionRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Accepted")
                        .HasColumnType("integer")
                        .HasColumnName("accepted");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<string>("Detail")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("detail");

                    b.Property<int>("Duplicates")
                        .HasColumnType("integer")
                        .HasColumnName("duplicates");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("outcome");

                    b.Property<int>("Rejected")
                        .HasColumnType("integer")
                        .HasColumnName("rejected");

                    b.Property<int>("RowsRead")
                        .HasColumnType("integer")
                        .HasColumnName("rows_read");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.HasKey("Id");

                    b.HasIndex("Source", "Outcome", "StartedAt")
                        .HasDatabaseName("ix_ingestion_runs_source_outcome_started_at");

                    b.ToTable("ingestion_runs", (string)null);
                });

            modelBuilder.Entity("Remedin.Domain.Medicines.Medicine", b =>
                {
                    b.Property<string>("RegistrationNumber")
                        .HasMaxLength(9)
                        .HasColumnType("character(9)")
                        .HasColumnName("registration_number")
                        .IsFixedLength();

                    b.Property<string>("ActiveIngredient")
                        .HasColumnType("text")
                        .HasColumnName("active_ingredient");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("text")
                        .HasColumnName("manufacturer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PrescriptionBand")
                        .HasColumnType("text")
                        .HasColumnName("prescription_band");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("TherapeuticClassCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("therapeutic_class_code");

                    b.Property<string>("TherapeuticClassName")
                        .HasColumnType("text")
                        .HasColumnName("therapeutic_class_name");

                    b.HasKey("RegistrationNumber");

                    b.ToTable("medicines", (string)null);
                });

            modelBuilder.Entity("Remedin.Domain.Medicines.Medicine", b =>
                {
                    b.OwnsMany("Remedin.Domain.Medicines.Presentation", "Presentations", b1 =>
                        {
                            b1.Property<string>("registration_number")
                                .HasColumnType("character(9)");

                            b1.Property<string>("GgremCode")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("ggrem_code");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("description");

                            b1.Property<bool>("HospitalOnly")
                                .HasColumnType("boolean")
                                .HasColumnName("hospital_only");

                            b1.Property<bool>("SoldRecently")
                                .HasColumnType("boolean")
                                .HasColumnName("sold_recently");

                            b1.HasKey("registration_number", "GgremCode");

                            b1.ToTable("presentations", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("registration_number");

                            b1.OwnsMany("Remedin.Domain.Medicines.Price", "Prices", b2 =>
                                {
                                    b2.Property<string>("registration_number")
                                        .HasColumnType("character(9)");

                                    b2.Property<string>("ggrem_code")
                                        .HasColumnType("character varying(20)");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(12, 2)
                                        .HasColumnType("numeric(12,2)")
                                        .HasColumnName("amount");

                                    b2.Property<bool>("FreeTradeZone")
                                        .HasColumnType("boolean")
                                        .HasColumnName("free_trade_zone");

                                    b2.Property<decimal?>("IcmsRate")
                                        .HasPrecision(4, 2)
                                        .HasColumnType("numeric(4,2)")
                                        .HasColumnName("icms_rate");

                                    b2.Property<string>("Kind")
                                        .IsRequired()
                                        .HasMaxLength(10)
                                        .HasColumnType("character varying(10)")
                                        .HasColumnName("kind");

                                    b2.HasKey("registration_number", "ggrem_code", "Id");

                                    b2.HasIndex("registration_number", "ggrem_code", "Kind", "IcmsRate")
                                        .HasDatabaseName("ix_prices_presentation_kind_rate");

                                    b2.ToTable("prices", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("registration_number", "ggrem_code");
                                });

                            b1.Navigation("Prices");
                        });

                    b.Navigation("Presentations");
                });
#pragma warning restore 612, 618
        }
    }
}
